name: Version Bump

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  version-bump:
    name: Version bump before publishing extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Automated Version Bump
        id: version
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "🔼 bump(v): version to {{version}} [skip ci]"

      - name: Create Tag
        id: create_tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
          tag_name: "v.${{ github.event.pull_request.head.ref }}"
