name: Version Bump

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  version-bump:
    name: Version bump before publishing extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Automated Version Bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "🔼 bump(v): version to {{version}} [skip ci]"
